---
include:
  - board: nice_nano@2.0.0
    shield: settings_reset

  # Sofle 2.0w Dongle (Central)
  - board: nice_nano@2.0.0
    shield: sofle_dongle nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  # Sofle 2.0w Peripherals
  - board: nice_nano@2.0.0
    shield: sofle_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano@2.0.0
    shield: sofle_right nice_view_adapter nice_view
