file_format: "1"
id: corax56
name: Corax56
type: shield
url: https://github.com/dnlbauer/corax56-keyboard
requires: [pro_micro]
features:
  - keys
  - encoder
siblings:
  - corax56_left
  - corax56_right
