manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: splitencoder
      url-base: https://github.com/infused-kim
  projects:
    - name: zmk
      remote: splitencoder
      revision: main
      import: app/west.yml
  self:
    path: config
