file_format: "1"
id: splitreus50
name: splitreus50
type: shield
url: https://github.com/mannkind/splitreus50
requires: [pro_micro]
features:
  - keys
siblings:
  - splitreus50_left
  - splitreus50_right
