name: Build Firmware

on:
  push:
  schedule:
    - cron: "30 13 * * *"
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/unified-zmk-config-template/blob/main/.github/workflows/build.yml@main
