name: Build Firmware

on:
  push:
  schedule:
    - cron: "30 13 * * *"
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  build-no-sc:
    uses: mannkind/zmk/.github/workflows/build-user-config.yml@no-sc-patch
